version: "3"

services:
  app:
    container_name: gitea
    environment:
        - POSTGRES_USER=root
        - POSTGRES_DB=gitea
        - DB_TYPE=postgres
        - DB_HOST=localhost:5432
    volumes:
        - ./data:/data
        - ./data/postgres:/var/lib/postgresql/data
    image: local-gitea
    ports:
        - 3000:3000
    networks:
      - proxy

networks:
  proxy:
    external: true
