version: "3"

services:
  app:
    container_name: gitea
    env_file:
      - .env
    volumes:
        - ./data:/data
        - ./data/postgres:/var/lib/postgresql/data
    image: local-gitea
    ports:
        - 3000:3000
    networks:
      - proxy

networks:
  proxy:
    external: true
