log_level = "info"

log_target = "stdout"

activate_listeners= true
command_socket = "./sock"
saved_state = "./state.json"
max_connections = 1028

[[listeners]]
protocol = "http"
address = "0.0.0.0:80"

[[listeners]]
protocol = "https"
address = "0.0.0.0:443"


[applications]
[applications.gitea]
protocol = "http"
#load_balancing_policy="roundrobin"
https_redirect = true
frontends = [
  { address = "0.0.0.0:80", hostname = "gitea.jimbertesting.be" },
  { address = "0.0.0.0:443", hostname = "gitea.jimbertesting.be", certificate = "/etc/sozu/certs/cert.pem", key = "/etc/sozu/certs/privkey.pem", certificate_chain = "/etc/sozu/certs/fullchain.pem" },
]

## TODO set backend up using docker dns
backends = [
  { address = "172.18.0.2:3000" }
]
