version: "3"

services:
  db:
    image: mysql/mysql-server:8.0
    # read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-root-password
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mmuser_password
      - MYSQL_DATABASE=mattermost
    networks:
      - mattermost_net
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    image: mattermost-docker-mysql_app
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority (link: https://github.com/mattermost/mattermost-server/issues/13059)
      # - <path_to_your_gitlab_pki>/pki_chain.pem:/etc/ssl/certs/pki_chain.pem:ro
    environment:
      # set same as db credentials and dbname
      - DB_PORT_NUMBER=3306
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - DB_HOST=db

      # use the credentials you've set above, in the format:
      # MM_SQLSETTINGS_DATASOURCE=${MM_USERNAME}:${MM_PASSWORD}@tcp(db:3306)/${MM_DBNAME}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
      - MM_SQLSETTINGS_DATASOURCE=mmuser:mmuser_password@tcp(db:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s

      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json
    networks:
      - mattermost_net
      - proxy

  web:
    image: mattermost-docker-mysql_web
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mattermost_net
      - proxy
    ports:
      - 80:80

networks:
  mattermost_net:
  proxy:
    external: true
